# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/ygelfand/posterlink/internal/config.Version={{.Version}}
      - -X github.com/ygelfand/posterlink/internal/config.GitCommit={{.Commit}}
      - -X github.com/ygelfand/posterlink/internal/config.BuildDate={{.Date}}

archives:
  - formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

dockers_v2:
  - images:
      - ghcr.io/ygelfand/posterlink
    tags:
      - "{{ .Version }}"
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile.goreleaser
    labels:
      org.opencontainers.image.source: https://github.com/ygelfand/posterlink
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"

release:
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
